set -g mouse on

set -g base-index 1

set -g status-left-length 40
set -g status-right-length 80

bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

set -g history-limit 50000

set -g set-clipboard on
